/**
 * Created by hongbinfu
 * 与后台交互的接口定义
 */

var API_PREFIX="index.php?";
var API={
    log:{
        getAdminLogList:API_PREFIX+'_c=Log&_a=getAdminLog',
        getClientLogList:API_PREFIX+'_c=Log&_a=getClientLog',
        getProcessLogList:API_PREFIX+'_c=Log&_a=getProcessLog',
        getLogList:API_PREFIX+'_c=Log&_a=getLogList',
        getDecryptDetail:API_PREFIX+'_c=Log&_a=getDecryptDetail',
        getAuthorizeDetail:API_PREFIX+'_c=Log&_a=getAuthorizeDetail',
        getEmailDetail:API_PREFIX+'_c=Log&_a=getEmailDetail',
        getFileSendDetail:API_PREFIX+'_c=Log&_a=getFileSendDetail',
        getDecryptApplyDetail:API_PREFIX+'_c=Log&_a=getDecryptApplyDetail',
        getFileApplyDetail:API_PREFIX+'_c=Log&_a=getFileApplyDetail',

        getClientLogDetail:API_PREFIX+'_c=Log&_a=getClientLogDetail2',
        getServerLogDetail:API_PREFIX+'_c=Log&_a=getServerLogDetail2'


    },
    role:{
        addGroupPage:API_PREFIX+'_c=Role&_a=addGroupPage',
        addGroup:API_PREFIX+'_c=Role&_a=addGroup',
        editGroup:API_PREFIX+'_c=Role&_a=editGroup',
        delGroup:API_PREFIX+'_c=Role&_a=delGroup',
        editGroupPage:API_PREFIX+'_c=Role&_a=editGroupPage',
        getRoleTree:API_PREFIX+'_c=Role&_a=getRoleTree',
        getRoleTypeTree:API_PREFIX+'_c=Role&_a=getRoleTypeTree',
        getRoleList:API_PREFIX+'_c=Role&_a=getRoleList',
        addRoleAndType:API_PREFIX+'_c=Role&_a=addRoleAndType',
        editRole:API_PREFIX+'_c=Role&_a=editRole',
        delRole:API_PREFIX+'_c=Role&_a=delRole',
        applyRole:API_PREFIX+'_c=Role&_a=applyRole',
        disableRole:API_PREFIX+'_c=Role&_a=disableRole',
        exportRole:API_PREFIX+'_c=Role&_a=exportRole',
        importRole:API_PREFIX+'_c=Role&_a=importRole',
        getUserGroupTree:API_PREFIX+'_c=Role&_a=getUserGroupTree'
    },
    setting:{
        //获取设置界面菜单列表树
        getSettingTree:API_PREFIX+'_c=Setting&_a=getSettingTree',
        //获取业务设置
        getBusinessSetting:API_PREFIX+'_c=Setting&_a=getBusinessSetting',
        //设置业务设置
        setBusinessSetting:API_PREFIX+'_c=Setting&_a=setBusinessSetting',
        //获取其他设置
        getOtherSetting:API_PREFIX+'_c=Setting&_a=getOtherSetting',
        //设置其他设置
        setOtherSetting:API_PREFIX+'_c=Setting&_a=setOtherSetting',
        setAdsSetting:API_PREFIX+'_c=Setting&_a=setAdsSetting',
        //获取流程设置
        getProcessSetting:API_PREFIX+'_c=Setting&_a=getProcessSetting',
        //设置流程设置
        setProcessSetting:API_PREFIX+'_c=Setting&_a=setProcessSetting',
        //重置流程设置
        resetProcessSetting:API_PREFIX+'_c=Setting&_a=resetProcessSetting',
        getProcessApplyUserGroupTree:API_PREFIX+'_c=Setting&_a=getProcessApplyUserGroupTree',
        //获取员工组树
        getUserGroupTree:API_PREFIX+'_c=Setting&_a=getUserGroupTree',
        getProcessStepUserGroupTree:API_PREFIX+'_c=Setting&_a=getProcessStepUserGroupTree',
        //获取系统自带的流程 必须的传参 type
        getSystemProcess:API_PREFIX+'_c=Setting&_a=getSystemProcess',
        getEmailWhiteList:API_PREFIX+'_c=Setting&_a=getEmailWhiteList',
        addWhiteListPage:API_PREFIX+'_c=Setting&_a=addWhiteListPage',
        saveWhiteList:API_PREFIX+'_c=Setting&_a=saveWhiteList',
        deleteWhiteList:API_PREFIX+'_c=Setting&_a=deleteWhiteList',
        editWhiteListPage:API_PREFIX+'_c=Setting&_a=editWhiteListPage',
        importWhiteList:API_PREFIX+'_c=Setting&_a=importWhiteList',
        exportWhiteList:API_PREFIX+'_c=Setting&_a=exportWhiteList',
        getRoleTree:API_PREFIX+'_c=Setting&_a=getRoleTree',
        getWorkModeList:API_PREFIX+'_c=Setting&_a=getWorkModeList',
        workModePage:API_PREFIX+'_c=Setting&_a=workModePage',
        saveWorkMode:API_PREFIX+'_c=Setting&_a=saveWorkMode',
        deleteWorkMode:API_PREFIX+'_c=Setting&_a=deleteWorkMode',
        getNoPolicyRoleTree:API_PREFIX+'_c=Setting&_a=getNoPolicyRoleTree'
    },
    strategy:{
        getStrategyGroupTree:API_PREFIX+'_c=Strategy&_a=getStrategyGroupTree',
        addGroupPage:API_PREFIX+'_c=Strategy&_a=addGroupPage',
        editGroupPage:API_PREFIX+'_c=Strategy&_a=editGroupPage',
        getStrategyList:API_PREFIX+'_c=Strategy&_a=getStrategyList',
        addStrategy:API_PREFIX+'_c=Strategy&_a=addStrategy',
        editStrategy:API_PREFIX+'_c=Strategy&_a=editStrategy',
        delStrategy:API_PREFIX+'_c=Strategy&_a=delStrategy',
        applyStrategy:API_PREFIX+'_c=Strategy&_a=applyStrategy',
        editGroupStrategy:API_PREFIX+'_c=Strategy&_a=editGroupStrategy',
        //下发策略到组
        copyPolicyToGroup:API_PREFIX+'_c=Strategy&_a=copyStrategyToGroup',
        copyGroupPolicyToGroup:API_PREFIX+'_c=Strategy&_a=copyGroupStrategyToGroup',
        importStrategy:API_PREFIX+'_c=Strategy&_a=importStrategy',
        exportStrategy:API_PREFIX+'_c=Strategy&_a=exportStrategy',
        getUserGroupTree:API_PREFIX+'_c=Strategy&_a=getUserGroupTree',
        delGroupStrategy:API_PREFIX+'_c=Strategy&_a=delGroupStrategy',
        syncStrategy:API_PREFIX+'_c=Strategy&_a=syncStrategy',
        //改变组策略的排序
        changeGroupStrategyOrder:API_PREFIX+'_c=Strategy&_a=changeGroupStrategyOrder',
        groupStrategyToTop:API_PREFIX+'_c=Strategy&_a=groupStrategyToTop',
        groupStrategyToBottom:API_PREFIX+'_c=Strategy&_a=groupStrategyToBottom'
    },
    user:{
        //部门树（用户分组）
        getDepartmentTree:API_PREFIX+'_c=UserGroup&_a=getUserGroupTree',
        //删除部门（分组）
        delDepartments:API_PREFIX+'_c=UserGroup&_a=delUserGroup',
        //添加部门
        addDepartment:API_PREFIX+'_c=UserGroup&_a=addUserGroup',
        addRootDepartment:API_PREFIX+'_c=UserGroup&_a=addUserRootGroup',
        editDepartment:API_PREFIX+'_c=UserGroup&_a=editUserGroup',
        //用户列表（Grid）
        getUserList:API_PREFIX+'_c=User&_a=getUserList',
        delUsers:API_PREFIX+'_c=User&_a=delUser',
        editUser:API_PREFIX+'_c=User&_a=editUser',
        addUser:API_PREFIX+'_c=User&_a=addUser',
        //生成离线授权文件
        generateOfflineFile:API_PREFIX+'_c=User&_a=generateOfflineFile',
        importUser:API_PREFIX+'_c=User&_a=importUser',
        exportUser:API_PREFIX+'_c=User&_a=exportUser',
        getRoleTree:API_PREFIX+'_c=User&_a=getRoleTree'
    },
    login:{
        doLogin:API_PREFIX+'_c=Login&_a=doLogin',
        doLogout:API_PREFIX+'_c=Login&_a=doLogout',
        keepAlive:API_PREFIX+'_c=Login&_a=keepAlive',
        changeMyPassword:API_PREFIX+'_c=Login&_a=changeMyPassword'
    },
    download:{
        download:API_PREFIX+"_c=Download&_a=download"
    },
    router:{
        autoLoadModule:API_PREFIX
    },
    system:{
        createMachineCode:API_PREFIX+'_c=System&_a=createMachineCode',
        doReg:API_PREFIX+'_c=System&_a=doReg',
        makeUninstall:API_PREFIX+'_c=System&_a=makeUninstall',
        canNotSupport:API_PREFIX+"_c=Index&_a=canNotSupport"
    },
    behaviorControl:{
        getMenu:API_PREFIX+"_c=behaviorControl&_a=getMenu",
        getList:API_PREFIX+"_c=behaviorControl&_a=getList",
        addPage:API_PREFIX+"_c=behaviorControl&_a=addPage",
        addWebItemPage:API_PREFIX+"_c=behaviorControl&_a=addWebItemPage",
        addIMItemPage:API_PREFIX+"_c=behaviorControl&_a=addIMItemPage",
        editPage:API_PREFIX+"_c=behaviorControl&_a=editPage",
        getUserTree:API_PREFIX+"_c=behaviorControl&_a=getUserTree",
        bindUserOrGroupPolicy:API_PREFIX+"_c=behaviorControl&_a=bindUserOrGroupPolicy",
        unbindUserOrGroupPolicy:API_PREFIX+"_c=behaviorControl&_a=unbindUserOrGroupPolicy",
        add:API_PREFIX+"_c=behaviorControl&_a=add",
        edit:API_PREFIX+"_c=behaviorControl&_a=edit",
        del:API_PREFIX+"_c=behaviorControl&_a=delete",
        export_data:API_PREFIX+"_c=behaviorControl&_a=export"
    }
};



